# Generated by Django 5.2.15 on 2026-07-10 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='scan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('PING', 'Ping Scan'), ('TCP', 'TCP Scan'), ('UDP', 'UDP Scan'), ('FULL', 'Full Scan')], default='PING', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Running', max_length=20),
        ),
    ]
